-- MySQL Script generated by MySQL Workbench
-- Thu Aug 27 08:27:01 2020
-- Model: New Model    Version: 0.0.3
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS,
  UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
  FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE,
  SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema segchamados
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema segchamados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `segchamados` DEFAULT CHARACTER SET utf8;
USE `segchamados`;
-- -----------------------------------------------------
-- Table `segchamados`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segchamados`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(245) NOT NULL,
  `permissions` VARCHAR(245) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `segchamados`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segchamados`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(245) NOT NULL,
  `user` VARCHAR(245) NOT NULL,
  `passwd` VARCHAR(245) NOT NULL,
  `email` VARCHAR(245) NOT NULL,
  `telefone` VARCHAR(245) NOT NULL,
  `actived` VARCHAR(245) NULL DEFAULT '1',
  `last_acess` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `role_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_roles1_idx` (`role_id` ASC),
  INDEX `index_nome` USING BTREE (`nome` ASC),
  INDEX `index_login` USING BTREE (`user` ASC),
  UNIQUE INDEX `login_UNIQUE` (`user` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  CONSTRAINT `fk_users_roles1` FOREIGN KEY (`role_id`) REFERENCES `segchamados`.`roles` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `segchamados`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segchamados`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(245) NOT NULL,
  `nome_fantasia` VARCHAR(245) NOT NULL,
  `cnpj_cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(245) NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_cliente` USING BTREE (`razao_social` ASC),
  INDEX `fk_clientes_users1_idx` (`user_id` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`razao_social` ASC),
  UNIQUE INDEX `cnpj_cpf_UNIQUE` (`cnpj_cpf` ASC),
  CONSTRAINT `fk_clientes_users1` FOREIGN KEY (`user_id`) REFERENCES `segchamados`.`users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `segchamados`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segchamados`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(245) NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categorias_users1_idx` (`user_id` ASC),
  INDEX `index_categoria` USING BTREE (`nome` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_categorias_users1` FOREIGN KEY (`user_id`) REFERENCES `segchamados`.`users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `segchamados`.`sub_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segchamados`.`sub_categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `categoria_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sub_categorias_categorias1_idx` (`categoria_id` ASC),
  INDEX `fk_sub_categorias_users1_idx` (`user_id` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  CONSTRAINT `fk_sub_categorias_categorias1` FOREIGN KEY (`categoria_id`) REFERENCES `segchamados`.`categorias` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_sub_categorias_users1` FOREIGN KEY (`user_id`) REFERENCES `segchamados`.`users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `segchamados`.`chamados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segchamados`.`chamados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ticket` VARCHAR(245) NOT NULL,
  `user_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `categorias_id` INT NOT NULL,
  `sub_categorias_id` INT NOT NULL,
  `status` VARCHAR(245) NOT NULL,
  `assunto` VARCHAR(245) NOT NULL,
  `conteudo` LONGTEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chamado_users1_idx` (`user_id` ASC),
  INDEX `fk_chamados_categorias1_idx` (`categorias_id` ASC),
  INDEX `fk_chamados_sub_categorias1_idx` (`sub_categorias_id` ASC),
  INDEX `index_ticket` (`ticket` ASC),
  INDEX `fk_chamados_clientes1_idx` (`cliente_id` ASC),
  INDEX `index_created_at` (`created_at` ASC),
  CONSTRAINT `fk_chamado_users1` FOREIGN KEY (`user_id`) REFERENCES `segchamados`.`users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_chamados_categorias1` FOREIGN KEY (`categorias_id`) REFERENCES `segchamados`.`categorias` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_chamados_sub_categorias1` FOREIGN KEY (`sub_categorias_id`) REFERENCES `segchamados`.`sub_categorias` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_chamados_clientes1` FOREIGN KEY (`cliente_id`) REFERENCES `segchamados`.`clientes` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `segchamados`.`modelos_chamados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segchamados`.`modelos_chamados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria_id` INT NOT NULL,
  `sub_categoria_id` INT NOT NULL,
  `assunto` VARCHAR(245) NOT NULL,
  `conteudo` LONGTEXT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modelos_chamados_users1_idx` (`user_id` ASC),
  INDEX `fk_modelos_chamados_categorias1_idx` (`categoria_id` ASC),
  INDEX `fk_modelos_chamados_sub_categorias1_idx` (`sub_categoria_id` ASC),
  CONSTRAINT `fk_modelos_chamados_users1` FOREIGN KEY (`user_id`) REFERENCES `segchamados`.`users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_modelos_chamados_categorias1` FOREIGN KEY (`categoria_id`) REFERENCES `segchamados`.`categorias` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_modelos_chamados_sub_categorias1` FOREIGN KEY (`sub_categoria_id`) REFERENCES `segchamados`.`sub_categorias` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `segchamados`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segchamados`.`logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `type` VARCHAR(245) NOT NULL,
  `category` VARCHAR(245) NOT NULL,
  `error` TEXT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_logs_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_logs_users1` FOREIGN KEY (`user_id`) REFERENCES `segchamados`.`users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `segchamados`.`cliente_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segchamados`.`cliente_has_user` (
  `cliente_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`cliente_id`, `user_id`),
  INDEX `fk_clientes_has_users_users1_idx` (`user_id` ASC),
  INDEX `fk_clientes_has_users_clientes1_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_clientes_has_users_clientes1` FOREIGN KEY (`cliente_id`) REFERENCES `segchamados`.`clientes` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_has_users_users1` FOREIGN KEY (`user_id`) REFERENCES `segchamados`.`users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `segchamados`.`acompanhamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segchamados`.`acompanhamentos` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `chamado_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_acompanhamentos_chamados1_idx` (`chamado_id` ASC),
  INDEX `fk_acompanhamentos_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_acompanhamentos_chamados1` FOREIGN KEY (`chamado_id`) REFERENCES `segchamados`.`chamados` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_acompanhamentos_users1` FOREIGN KEY (`user_id`) REFERENCES `segchamados`.`users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `segchamados`.`atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segchamados`.`atividades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `atividade` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tarefas_users1_idx` (`user_id` ASC),
  INDEX `fk_tarefas_clientes1_idx` (`cliente_id` ASC),
  INDEX `index_created_at` (`created_at` ASC),
  CONSTRAINT `fk_tarefas_users1` FOREIGN KEY (`user_id`) REFERENCES `segchamados`.`users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarefas_clientes1` FOREIGN KEY (`cliente_id`) REFERENCES `segchamados`.`clientes` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `segchamados`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segchamados`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `owner_user_id` INT NOT NULL,
  `open_by_user_id` INT NOT NULL,
  `status` VARCHAR(245) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tasks_clientes1_idx` (`cliente_id` ASC),
  INDEX `fk_tasks_users1_idx` (`owner_user_id` ASC),
  INDEX `fk_tasks_users2_idx` (`open_by_user_id` ASC),
  CONSTRAINT `fk_tasks_clientes1` FOREIGN KEY (`cliente_id`) REFERENCES `segchamados`.`clientes` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_users1` FOREIGN KEY (`owner_user_id`) REFERENCES `segchamados`.`users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_users2` FOREIGN KEY (`open_by_user_id`) REFERENCES `segchamados`.`users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `segchamados`.`acm_tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `segchamados`.`acm_tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `created_at` VARCHAR(45) NOT NULL,
  `updated_at` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_acm_tasks_tasks1_idx` (`task_id` ASC),
  INDEX `fk_acm_tasks_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_acm_tasks_tasks1` FOREIGN KEY (`task_id`) REFERENCES `segchamados`.`tasks` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_acm_tasks_users1` FOREIGN KEY (`user_id`) REFERENCES `segchamados`.`users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;