const Insert = [
  {
    id: "nome",
    label: "Nome Completo",
    required: true,
    autofocus: true,
    margin: "normal",
    type: "text",
    option: "input",
    value: "",
  },
  {
    id: "passwd",
    label: "Senha",
    required: true,
    margin: "normal",
    type: "password",
    option: "input",
    value: "******",
  },
  {
    id: "email",
    label: "Email",
    required: true,
    margin: "normal",
    type: "email",
    option: "input",
    value: "",
  },
  {
    id: "user",
    label: "Username",
    required: true,
    margin: "normal",
    type: "email",
    option: "input",
    value: "",
  },
  {
    id: "telefone",
    label: "Telefone",
    required: true,
    margin: "normal",
    type: "email",
    option: "input",
    value: "",
  },
];

const Update = [
  {
    id: "nome",
    label: "Nome Completo",
    required: true,
    autofocus: true,
    margin: "normal",
    type: "text",
    option: "input",
    value: "",
  },
  {
    id: "passwd",
    label: "Senha",
    required: true,
    margin: "normal",
    type: "password",
    option: "input",
    value: "******",
  },
  {
    id: "email",
    label: "Email",
    required: true,
    margin: "normal",
    type: "email",
    option: "input",
    value: "",
  },
  {
    id: "user",
    label: "Username",
    required: true,
    margin: "normal",
    type: "email",
    option: "input",
    value: "",
    disabled: true,
  },
  {
    id: "telefone",
    label: "Telefone",
    required: true,
    margin: "normal",
    type: "email",
    option: "input",
    value: "",
  },
];

export default { Insert, Update };
